language: go

go:
- 1.7.6
- 1.8.3
- 1.9beta2

env:
  matrix:
  - PACKAGE_TYPE=deb
  - PACKAGE_TYPE=rpm

script: make test

before_install:
  - sudo apt-get -q update
  - sudo apt-get install -y make gcc rpm

before_deploy:
  - gem install fpm --no-document
  - VERSION=${TRAVIS_TAG:=$(cat ./VERSION)} make pkg/$PACKAGE_TYPE
  - sed -i'' -e "s/\PACKAGE_TYPE/${PACKAGE_TYPE}/" descriptor.json
  - sed -i'' -e "s/\VERSION/${TRAVIS_TAG:=$(cat ./VERSION)}/" descriptor.json
  - sed -i'' -e "s/\DATE/$(date +%Y-%m-%d)/" descriptor.json
  - if [ $TRAVIS_TAG ]; then SUBJECT=tactycal; else SUBJECT=3fs-talam; fi; sed -i'' -e "s/BINTRAY_SUBJECT/${SUBJECT}/" descriptor.json
  - if [ $TRAVIS_TAG ]; then SUBJECT=tactycal; else SUBJECT=3fs-talam; fi; echo "SUBJECT=${SUBJECT}"

deploy:
  # "production" deploy
  - provider: bintray
    user: talam3fs
    key: $BINTRAY_API_KEY
    file: descriptor.json
    skip_cleanup: true
    on:
      go: 1.8.3
      tags: true

  # "staging" deploy
  - provider: bintray
    user: talam3fs
    key: $BINTRAY_API_KEY
    file: descriptor.json
    skip_cleanup: true
    on:
      go: 1.8.3
      branch: master

  # "simulated" deploy
  - provider: script
    script: ls -laR .
    on:
      go: 1.8.3
      all_branches: true
