language: go

go:
- 1.7.5
- 1.8.1

env:
  matrix:
  - PACKAGE_MANAGER=dpkg
  - PACKAGE_MANAGER=rpm

script: make test

before_install:
  - sudo apt-get -q update
  - sudo apt-get install -y make gcc rpm

before_deploy:
  - gem install fpm --no-document
  - VERSION=${TRAVIS_TAG:=$(cat ./VERSION)} make pkg/$PACKAGE_MANAGER
  - sed -i'' -e "s/\PACKAGE_MANAGER/${PACKAGE_MANAGER}/" descriptor.json
  - sed -i'' -e "s/\VERSION/${TRAVIS_TAG:=$(cat ./VERSION)}/" descriptor.json
  - sed -i'' -e "s/\DATE/$(date +%Y-%m-%d)/" descriptor.json
  - if [ $TRAVIS_TAG ]; then SUBJECT=tactycal; else SUBJECT=3fs-talam; fi; sed -i'' -e "s/BINTRAY_SUBJECT/${SUBJECT}/" descriptor.json

deploy:
  # "production" deploy
  - provider: bintray
    user: talam3fs
    key: $BINTRAY_API_KEY
    file: descriptor.json
    skip_cleanup: true
    on:
      go: 1.8.1
      tags: true

  # "staging" deploy
  - provider: bintray
    user: talam3fs
    key: $BINTRAY_API_KEY
    file: descriptor.json
    skip_cleanup: true
    on:
      go: 1.8.1
      branch: master

  # "simulated" deploy
  - provider: script
    script: ls -laR .
    on:
      branch: deploy
      go: 1.8.1
