version: "2"
services:
  agentdebian:
    image: debian:jessie
    command: /usr/local/bin/tactycal -d
    volumes:
      - ./build/usr/bin/tactycal:/usr/local/bin/tactycal
      - ./my_conf.conf:/etc/tactycal/agent.conf
      - .state/debian:/var/opt/tactycal/state
    environment:
      - LABEL=debianenv

  agentubuntu:
    image: ubuntu:latest
    command: /usr/local/bin/tactycal -d
    volumes:
      - ./build/usr/bin/tactycal:/usr/local/bin/tactycal
      - ./my_conf.conf:/etc/tactycal/agent.conf
      - .state/ubuntu:/var/opt/tactycal/state
    environment:
      - LABEL=ubuntuenv

  agentrhel:
    image: richxsl/rhel7
    command: /usr/local/bin/tactycal -d
    volumes:
      - ./build/usr/bin/tactycal:/usr/local/bin/tactycal
      - ./my_conf.conf:/etc/tactycal/agent.conf
      - .state/rhel:/var/opt/tactycal/state

  agentcentos:
    image: centos:7
    command: /usr/local/bin/tactycal -d
    volumes:
      - ./build/usr/bin/tactycal:/usr/local/bin/tactycal
      - ./my_conf.conf:/etc/tactycal/agent.conf
      - .state/centos:/var/opt/tactycal/state

  agentopensuse:
    image: opensuse:42.2
    command: /usr/local/bin/tactycal -d
    volumes:
      - ./build/usr/bin/tactycal:/usr/local/bin/tactycal
      - ./my_conf.conf:/etc/tactycal/agent.conf
      - .state/opensuse:/var/opt/tactycal/state

  agentsles:
    image: gitlab.3fs.si:4567/tactycal/tactycal:sles12sp2
    command: /usr/local/bin/tactycal -d
    volumes:
      - ./build/usr/bin/tactycal:/usr/local/bin/tactycal
      - ./my_conf.conf:/etc/tactycal/agent.conf
      - .state/sles:/var/opt/tactycal/state

  agentamzn:
    image: amazonlinux:2016.09
    command: /usr/local/bin/tactycal -d
    volumes:
      - ./build/usr/bin/tactycal:/usr/local/bin/tactycal
      - ./my_conf.conf:/etc/tactycal/agent.conf
      - .state/amzn:/var/opt/tactycal/state
